### ISSUE TITLE
File Sharing

### ISSUE THREAD

**Issue by realchriswells** [DomosHaidou/MageVagrant#1]
I'm using this Vagrantfile as the base for other Magento projects, but I'm wondering if there is a way to change the Vagrantfile or the setup in one of the cookbooks so that I can access the Magento files in /srv/www/\* on my Windows 7 host machine?

Ideally I'd like to setup a new project in PHPStorm that can access the files and database, however I can't seem to access this.

I know that you can do synced_folders in Vagrantfiles, but I'm not sure how to go about setting this up so that it wouldn't affect the automatic Magento installation.

Any help/advice you can offer would be great on this.

Thanks!

EDIT: I tried changing cookbooks/vagrant_main/recipes/default.rb so that it installed Magento to the /vagrant/www/rest_of_path folder on the VM, however when I change this the SVN checkout doesn't work throwing up the following error: 
svn: Can't move '.svn/tmp/entries' to '/.svn/entries': Operation not permitted

**Comment by lfolco** [comment]
hi-

add this to the very end of your vagrant file:

Vagrant.configure("2") do |config|
  # other config here

  config.vm.synced_folder "../public_html", "/srv/www/magento.localhost.com/public_html", :owner=> 'vagrant', :group=>'www-data', :mount_options => ['dmode=775', 'fmode=775']
end

where 'public_html' is your local path. make sure the folder exists before starting vagrant.
